### ISSUE TITLE
dll is not valid

### ISSUE THREAD

**Issue by D-Asce** [Zai-Kun/reverse-engineered-chatgpt#12]
ctypes.CDLL("D:/chatgpt/reverse-engineered-chatgpt-main/re_gpt/funcaptcha_bin/windows_arkose.dll")
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.1\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
  File "C:\Program Files\Python311\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

**Comment by Zai-Kun** [comment]
Try downloading the funcaptcha binary manually.

Goto [funcaptcha binary release](https://github.com/Zai-Kun/reverse-engineered-chatgpt/releases/tag/funcaptcha_bin) and download the binary for Windows, and then replace the old binary in `path/to/re_gpt/funcaptcha_bin` with the newly downloaded one. In your case, the `funcaptcha_bin` folder is in `D:/chatgpt/reverse-engineered-chatgpt-main/re_gpt/`.

**Comment by Zai-Kun** [comment]
I'm going to assume the issue has been resolved. Open up the issue again if you are still facing it.
