### ISSUE TITLE
请问支持gpt4吗

### ISSUE THREAD

**Issue by jxyk2007** [Zai-Kun/reverse-engineered-chatgpt#15]
请问支持gpt4吗

**Comment by Zai-Kun** [comment]
Unfortunately, no because I don't have a GPT Plus account to add support for GPT4.

**Comment by jxyk2007** [comment]
我有plus 我的账号可以让你测试

**Comment by Zai-Kun** [comment]
> 我有plus 我的账号可以让你测试

如果您愿意与我共享您的帐户，我可以尝试。我在哪里可以联系到你们？

**Comment by jxyk2007** [comment]
> > 我有plus 我的账号可以让你测试
> 
> 如果您愿意与我共享您的帐户，我可以尝试。我在哪里可以联系到你们？
> 

jxyk2007@gmail.com
