### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by innerop** [Zai-Kun/reverse-engineered-chatgpt#18]
hey

nice work! 

does this provide access to GPT 3.5? 

I understand the limit is 5 requests every 3 hours?

**Comment by jxyk2007** [comment]
> hey
> 
> nice work!
> 
> does this provide access to GPT 3.5?
> 
> I understand the limit is 5 requests every 3 hours?

3.5没有次数限制。
4.0才有次数限制。
GPT-4
With DALL·E, browsing and analysis
Limit 40 messages / 3 hours

**Comment by innerop** [comment]
That's good news!

Does it require the user to be a ChatGPT Plus user and sign-in with their OpenAI username/password in order to access GPT4?
