### ISSUE TITLE
Monkey-patching official OpenAI module

### ISSUE THREAD

**Issue by sudoAlphaX** [Zai-Kun/reverse-engineered-chatgpt#2]
Is it possible to monkey-patch the official ChatGPT Python API using such a method? It will be useful if we could use the official module but with such an implementation.

**Comment by Zai-Kun** [comment]
> Is it possible to monkey-patch the official ChatGPT Python API using such a method? It will be useful if we could use the official module but with such an implementation.

I'm not sure, but the idea seems pretty good. I will look into it.

**Comment by Zai-Kun** [comment]
After scratching my head for a few hours, it seems pretty darn tough. Plus, I don't really see the point, so I'm gonna pass on it.

**Comment by sudoAlphaX** [comment]
I have never used the ChatGPT API, but arent there other modules that leverage the ChatGPT API in them. If if it true, then we can use other modules too effectively for free.

**Comment by Zai-Kun** [comment]
Oh yeah, good point. But it's not gonna be easy to do it. I will try again.

**Comment by Zai-Kun** [comment]
How about we start fresh, just focusing on the chat feature? It seems simpler. We can then swap out the old API with this one in a virtual environment or something like that.

**Comment by Zai-Kun** [comment]
Here's the basic way to use the chat feature of the ChatGPT API:

```python
import openai 
openai.api_key = 'YOUR_API_KEY'
messages = [ {"role": "system", "content": 
			"You are a intelligent assistant."} ] 
while True: 
	message = input("User : ") 
	if message: 
		messages.append( 
			{"role": "user", "content": message}, 
		) 
		chat = openai.ChatCompletion.create( 
			model="gpt-3.5-turbo", messages=messages 
		) 
	reply = chat.choices[0].message.content 
	print(f"ChatGPT: {reply}") 
	messages.append({"role": "assistant", "content": reply}) 
```

**Comment by sudoAlphaX** [comment]
> How about we start fresh, just focusing on the chat feature? It seems simpler. We can then swap out the old API with this one in a virtual environment or something like that.

yea that seems good. and by the way. But are there any other features?
> just focusing on the chat feature
What are you referencing?

**Comment by sudoAlphaX** [comment]
BTW, how about a new project that focuses on monkey-patching the openai api and redirecting chatgpt requests to an offline model like [gpt4free](https://github.com/xtekky/gpt4free)

**Comment by Zai-Kun** [comment]
> But are there any other features?

Things related to OpenAI, such as their other projects like DALL·E, etc.

> What are you referencing?

Basically, remove everything other than the chat feature because it's not going to work anyway since they all need the API key.

**Comment by Zai-Kun** [comment]
> BTW, how about a new project that focuses on monkey-patching the openai api and redirecting chatgpt requests to an offline model like [gpt4free](https://github.com/xtekky/gpt4free) I think it will be pretty interesting considering the number of models we can use instead of only ChatGPT

I'm not sure. Seems a little hard, we'll think about that later.

**Comment by sudoAlphaX** [comment]
> Basically, remove everything other than the chat (ChatGPT) feature because it's not going to work anyway since they all need the API key.

oh i understand

**Comment by sudoAlphaX** [comment]
> I'm not sure. Seems a little hard, we'll think about that later.

alright. If you decide to work on it, I'll contribute too.

**Comment by Zai-Kun** [comment]
So, where do we start?

**Comment by sudoAlphaX** [comment]
I think we need a fresh repo with a function that when called with a prompt and the ai engine, will return the response from chatgpt, through web prompts. it would be nice if the function was similar to the official openai chatgpt function in terms of args.

**Comment by sudoAlphaX** [comment]
By the way, I found 2 other projects that have the done the same thing.
we could use those or yours.
the part we need to focus on is manipulating the official openai module to redirect requests to our module.

[Repo 1](https://github.com/kurtseifried/ChatGPT-API)
[Repo 2](https://github.com/acheong08/ChatGPT)

**Comment by Zai-Kun** [comment]
> I think we need a fresh repo with a function that when called with a prompt and the ai engine, will return the response from chatgpt, through web prompts. it would be nice if the function was similar to the official openai chatgpt function in terms of args.

Yeah cool, but there's a little issue. I don't think this reverse-engineered API is working anymore. The API is returning this error:

{"error": "Our systems have detected unusual activity from your system. Please try again later."}

Can you confirm if it returns the same thing for you too?

**Comment by Zai-Kun** [comment]
>you can try a chatgpt proxy, it's a repo in github.

Oh yeah, I remember something like that.

**Comment by sudoAlphaX** [comment]
{'message': None, 'conversation_id': 'ae2ab303-ca88-456a-8382-ddf700144609', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}

Same issue here, and it's the first time i'm using the script

**Comment by Zai-Kun** [comment]
> {'message': None, 'conversation_id': 'ae2ab303-ca88-456a-8382-ddf700144609', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}
> 
> Same issue here, and it's the first time i'm using the script

It used to work just fine before.

After looking into it more, I have found that you need to include something called an 'arkose_token' in the payload. For now, let's put 'Monkey-patching' on hold, and let's focus on making the API work again.

**Comment by sudoAlphaX** [comment]
alright
