### ISSUE TITLE
gpt-4 not working

### ISSUE THREAD

**Issue by Myte01** [Zai-Kun/reverse-engineered-chatgpt#24]
There's no response from gpt-4 model

**Comment by Zai-Kun** [comment]
I do not recommend using gpt-4 as it requires an arkose-token which is related to captchas. Sometimes it doesn't work because of that. There is nothing much I can do, gpt-4 has captcha protection on it. I recommend only using gpt-3.

**Comment by Myte01** [comment]
Now solved, I modify arkose generator. Thanks !!

**Comment by Zai-Kun** [comment]
> Now solved, I modified arkose generator. Thanks !!

Can you please tell me what did you do to make it work? It would be great if you do.

**Comment by Myte01** [comment]
I use your [py-arkose-token-generator](https://github.com/Zai-Kun/py-arkose-token-generator) instead of arkose-token-generator function.
