### ISSUE TITLE
UnexpectedResponseError

### ISSUE THREAD

**Issue by iamsky13** [Zai-Kun/reverse-engineered-chatgpt#27]
I started playing with basic examples and failed to run it

```
Exception has occurred: UnexpectedResponseError
An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.
This is what the server returned: {"wss_url":"wss://chatgpt-async-webps-prod-eastus-23.webpubsub.azure.com/client/hubs/conversations?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2NoYXRncHQtYXN5bmMtd2VicHMtcHJvZC1lYXN0dXMtMjMud2VicHVic3ViLmF6dXJlLmNvbS9jbGllbnQvaHVicy9jb252ZXJzYXRpb25zIiwiaWF0IjoxNzA3MDE1MDU4LCJleHAiOjE3MDcwMTg2NTgsInN1YiI6InVzZXItajE2a2RQSDFhS3ZQTWlnRjNzWGJlcTZpIn0.3_Gnx9QoHBqwY6v44jcuUiiPczggQrLIyt2om001GQI","expires_at":"2024-02-04T03:50:58.264613+00:00","conversation_id":"cb1ff950-ce37-47e6-a877-fc43f1a79514","response_id":"84ff9bef7c174d1e-BOS"}.
  File "D:\reverse-engineered-chatgpt-3.0.1\reverse-engineered-chatgpt-3.0.1\examples\async_basic_example.py", line 28, in main
    async for message_chunk in conversation.chat(prompt):
  File "D:\reverse-engineered-chatgpt-3.0.1\reverse-engineered-chatgpt-3.0.1\examples\async_basic_example.py", line 34, in <module>
    asyncio.run(main())
re_gpt.errors.UnexpectedResponseError: An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.
This is what the server returned: {"wss_url":"wss://chatgpt-async-webps-prod-eastus-23.webpubsub.azure.com/client/hubs/conversations?access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwczovL2NoYXRncHQtYXN5bmMtd2VicHMtcHJvZC1lYXN0dXMtMjMud2VicHVic3ViLmF6dXJlLmNvbS9jbGllbnQvaHVicy9jb252ZXJzYXRpb25zIiwiaWF0IjoxNzA3MDE1MDU4LCJleHAiOjE3MDcwMTg2NTgsInN1YiI6InVzZXItajE2a2RQSDFhS3ZQTWlnRjNzWGJlcTZpIn0.3_Gnx9QoHBqwY6v44jcuUiiPczggQrLIyt2om001GQI","expires_at":"2024-02-04T03:50:58.264613+00:00","conversation_id":"cb1ff950-ce37-47e6-a877-fc43f1a79514","response_id":"84ff9bef7c174d1e-BOS"}.
```

![image](https://github.com/Zai-Kun/reverse-engineered-chatgpt/assets/20113442/dfca743d-f136-4f76-a020-fc101664c82a)

**Comment by waheedullahkhan001** [comment]
same

**Comment by gerkim62** [comment]
This issue is that chatgpt has changed how they handle messages. they are using wss instead. someone can please update this library so it can handle wss web scokets. my python skills are limited i would have done it.

**Comment by LastTherapy** [comment]
Same promlem

**Comment by Zai-Kun** [comment]
> This issue is that chatgpt has changed how they handle messages. they are using wss instead. someone can please update this library so it can handle wss web scokets. my python skills are limited i would have done it.

As you said, ChatGPT changed their backend infrastructure, now they are using websockets. But it seems like this change has only been made in some regions because for some people the re_gpt is still working (including me). And after monitoring ChatGPT's network traffic in my browser, no ebsocket connection was made, it's using the method it was using before. Thus, I can't debug this until the new changes have been applied in my region too.

**Comment by Zai-Kun** [comment]
https://github.com/Zai-Kun/reverse-engineered-chatgpt/issues/27#issuecomment-1983161935

**Comment by gerkim62** [comment]
Not really
![image](https://github.com/Zai-Kun/reverse-engineered-chatgpt/assets/72649107/5d9022b1-d9e7-488c-8b9e-41245e751fc3)

**Comment by waheedullahkhan001** [comment]
Your token is visible FYI

> Not really ![image](https://private-user-images.githubusercontent.com/72649107/312238291-5d9022b1-d9e7-488c-8b9e-41245e751fc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTU2ODMsIm5iZiI6MTcxMDI5NTM4MywicGF0aCI6Ii83MjY0OTEwNy8zMTIyMzgyOTEtNWQ5MDIyYjEtZDllNy00ODhjLThiOWUtNDEyNDVlNzUxZmMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDAyMDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNWI3OTEzNzYyYmYzMTM4N2NjMjlhOTNhMzUyZDFlY2NlZjg1OWY4MDJkNTQ4YTI3NWUxZjJjNjViNjQ5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eibCAsJ29JjfbnkneCJSt141O3liej5L-rTxP7f2o_w)

**Comment by gerkim62** [comment]
still not working

**Comment by LuciferM242** [comment]
not working for me eather

**Comment by waheedullahkhan001** [comment]
FYI

After I saw the latest PR merged I tried pulling the source code and installing using ``setup install`` but still:
```
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\playground\main.py", line 27, in <module>
    asyncio.run(main())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\PycharmProjects\playground\main.py", line 22, in main
    async for message in conversation.chat(prompt):
  File "C:\Users\Admin\PycharmProjects\playground\.venv\Lib\site-packages\re_gpt-3.0.2-py3.12.egg\re_gpt\async_chatgpt.py", line 142, in chat
    raise UnexpectedResponseError(error, server_response)
re_gpt.errors.UnexpectedResponseError: An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.
This is what the server returned: {"detail":"There was a problem with your chat request. Please use a different browser or try again later."}.
```

**Comment by Barrierml** [comment]
> FYI
> 
> After I saw the latest PR merged ( #33 ), I tried pulling the source code and installing using `setup install` but still:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\Admin\PycharmProjects\playground\main.py", line 27, in <module>
>     asyncio.run(main())
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 664, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "C:\Users\Admin\PycharmProjects\playground\main.py", line 22, in main
>     async for message in conversation.chat(prompt):
>   File "C:\Users\Admin\PycharmProjects\playground\.venv\Lib\site-packages\re_gpt-3.0.2-py3.12.egg\re_gpt\async_chatgpt.py", line 142, in chat
>     raise UnexpectedResponseError(error, server_response)
> re_gpt.errors.UnexpectedResponseError: An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.
> This is what the server returned: {"detail":"There was a problem with your chat request. Please use a different browser or try again later."}.
> ```

PR alreay pushed, wait approved, you can use it at https://github.com/Barrierml/reverse-engineered-chatgpt

**Comment by MahdeenSky** [comment]
still same problem

**Comment by MahdeenSky** [comment]
> > still same problem
> 
> Can you provide a return value for this API use your chatgpt account? https://chat.openai.com/backend-api/sentinel/chat-requirements

detail" : "Method Not Allowed"

**Comment by gerkim62** [comment]
> > still same problem
> 
> Can you provide a return value for this API use your chatgpt account? https://chat.openai.com/backend-api/sentinel/chat-requirements

using get or post?

**Comment by MahdeenSky** [comment]
> > > still same problem
> > 
> > 
> > Can you provide a return value for this API use your chatgpt account? https://chat.openai.com/backend-api/sentinel/chat-requirements
> 
> using get or post?

get

**Comment by waheedullahkhan001** [comment]
I found the request in network tab when loading ChatGPT:

{
    "persona": "chatgpt-freeaccount",
    "arkose": {
        "required": false,
        "dx": null
    },
    "turnstile": {
        "required": false
    },
    "token": "_**TRUNCATED**_"
}
