### ISSUE TITLE
chatgpt.py::decoded_json:: {...'error': 'Our systems have detected unusual activity from your system. Please try again later.'}

### ISSUE THREAD

**Issue by cocolacre** [Zai-Kun/reverse-engineered-chatgpt#3]
So, I've noticed you've updated(and then reversed) the README recently, saying that openai had changed their protocol.
Just for the record, here's the current state of the issue with this project.
Upon sending a prompt, we get the following content within the "decoded_json" from the server:
`{'message': None, 'conversation_id': '...', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}`

So be careful, folks, because they can probably ban your account due to this.

**Comment by Zai-Kun** [comment]
The thing is, now they require a token called 'arkose-token.' I am trying to find a way to generate it. Hopefully, it will be fixed soon.
