### ISSUE TITLE
Dell-E 3

### ISSUE THREAD

**Issue by raymerjacque** [Zai-Kun/reverse-engineered-chatgpt#30]
since it works on Chatgpt plus and supports GPT4, what about Dall-E3 ? that is included in chatgpt plus now. you can generate images directly in chat... so when will you guys add Dall-E support for the chatgpt plus options ?

**Comment by Zai-Kun** [comment]
I've no plans of adding support for other GPT Plus features as I do not own a GPT Plus account to test with and I don't have much time in my hands these days. If anyone decides to contribute, I would merge a PR with GPT plus features. But on my end, I'm not going to work on it anymore. I just might even deprecate it as a lot of people are complaining about it not being stable.
