### ISSUE TITLE
I think this got patched

### ISSUE THREAD

**Issue by ruinedm** [Zai-Kun/reverse-engineered-chatgpt#32]
re_gpt.errors.UnexpectedResponseError: An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.

**Comment by Zai-Kun** [comment]
https://github.com/Zai-Kun/reverse-engineered-chatgpt/issues/27#issuecomment-1983161935

**Comment by gerkim62** [comment]
this issue is not fixed yet
