### ISSUE TITLE
today, you can use ChatGPT without needing to sign up!

### ISSUE THREAD

**Issue by laosuan** [Zai-Kun/reverse-engineered-chatgpt#41]
Can this project be updated?

https://openai.com/blog/start-using-chatgpt-instantly

**Comment by gerkim62** [comment]
i think it is possible to update this library to no longer require the cookies

**Comment by Barrierml** [comment]
supported, you can use it firstly at https://github.com/Barrierml/reverse-engineered-chatgpt/tree/main

**Comment by laosuan** [comment]
thanks

**Comment by gerkim62** [comment]
someone to update readme to reflect this
